# Generated by Django 4.1.2 on 2022-10-29 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_song_date_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='Artist',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artist'),
            preserve_default=False,
        ),
    ]
